pipeline:
	  python3 scripts.pipeline.1_convert_matlab_to_python
	  python3 scripts.pipeline.2_time_frequency_analysis
	  python3 scripts.pipeline.3_id_modulated_chans
	  python3 scripts.pipeline.4_spectral_parameterization
	  python3 scripts.pipeline.5_compute_intersection
	  python3 scripts.pipeline.6_aggregate_results
	  python3 scripts.pipeline.7_permutation_stats

figures:


all: pipeline figures
